### ISSUE TITLE
Please help. Same problem. Need assistance

### ISSUE THREAD

**Issue by deshwalmahesh** [CVxTz/image_search_engine#11]
Hi, I am working on almost same thing as yours but the problem is that I have this data of images with text that I have to search. My problem is that how can I do it when I have more than 20M images? Please help. I have raised a question too.

[Manage Memory and Speed for Image Search Engine](https://datascience.stackexchange.com/questions/87256/how-to-manage-memory-constraint-and-increase-speed-for-1-vs-rest-image-similarit)

**Comment by CVxTz** [comment]
Use smaller sized vectors so you can load more images in memory.
You can also use fast knn algorithms like ball tree ( available in sklearn) in order to find the closest match.
