### ISSUE TITLE
How is positive branch being trained on Image + Text?

### ISSUE THREAD

**Issue by deshwalmahesh** [CVxTz/image_search_engine#14]
Looking at [your model code from here](https://github.com/CVxTz/image_search_engine/blob/master/code/model_triplet.py) in `def model()`, you treat `x1` as Image and the remaining `x2` , `x3` both as a Text model [while in your blog explanatio here](https://towardsdatascience.com/building-a-deep-image-search-engine-using-tf-keras-6760beedbad), you have said that
>The model takes 3 inputs: The image (which is the anchor), the image title+description ( the positive example) and the third input is some randomly sampled text (the negative example).

Can you please explain on this one?

**Comment by CVxTz** [comment]
Hello,

The image => x1
title+description => x2 => positive example
random text => x2 => negative example

Best,
