### ISSUE TITLE
Looking forward to the dataset and "../input/filtred_*.json released

### ISSUE THREAD

**Issue by yijiuzai** [CVxTz/image_search_engine#2]

**Comment by CVxTz** [comment]
Hello,
This json is derived from the data in
http://jmcauley.ucsd.edu/data/amazon/ Which
I don't own so I cant not upload it.
In each of the "../input/filtred_*.json" there is simply a list of
(image_path, text) tuples.
Best,

**Comment by yijiuzai** [comment]
Thank you

发自我的 iPhone

> 在 2019年11月29日，18:57，CVxTz <notifications@github.com> 写道：
> 
> Hello,
> This json is derived from the data in
> http://jmcauley.ucsd.edu/data/amazon/ Which
> I don't own so I cant not upload it.
> In each of the "../input/filtred_*.json" there is simply a list of
> (image_path, text) tuples.
> Best,
>
